### ISSUE TITLE
Kobo Glo: 'utf8' codec can't decode byte 0x92 in position 32: invalid start byte

### ISSUE THREAD

**Issue by bkqc** [jgoguen/calibre-kobo-driver#88] opened 2020-05-15 17:31 UTC
Since I upgraded to the latest version of the plugin, I keep getting this error when I connect my Kobo. The main problem is that now I can't access my reader at all through Calibre. Files are still accessible though Windows Explorer though.

calibre, version 4.16.0
plugin v.3.2.2
Kobo Glo v4.20.14622
ERROR: Error: Error communicating with device

'utf8' codec can't decode byte 0x92 in position 32: invalid start byte

Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 90, in run
  File "site-packages\calibre\gui2\device.py", line 513, in _books
  File "site-packages\calibre\devices\kobo\driver.py", line 1565, in books
  File "site-packages\calibre\devices\kobo\driver.py", line 3542, in get_debugging_title
  File "site-packages\calibre\devices\kobo\driver.py", line 3264, in get_pref
  File "calibre_plugins.kobotouch_extended.device.driver", line 113, in settings
  File "calibre_plugins.kobotouch_extended.common", line 95, in print_formatted_log
  File "calibre_plugins.kobotouch_extended.common", line 84, in _tag_args
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 32: invalid start byte

**Comment by bkqc** [comment] 2020-05-15 18:57
I get almost the same error when I click on Preferences/Metadata Plugboards

calibre, version 4.16.0
ERROR: Unhandled exception: <b>UnicodeDecodeError</b>:'utf8' codec can't decode byte 0x92 in position 32: invalid start byte

calibre 4.16 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: KePub Metadata Writer (3, 2, 2) && KoboTouchExtended (3, 2, 3) && Manage Series (1, 2, 9) && Find Duplicates (1, 6, 3) && KePub Metadata Reader (3, 2, 2) && Quality Check (1, 9, 11) && Kobo Utilities (2, 11, 0) && User Category (1, 5, 4)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\main.py", line 311, in show_plugin
  File "site-packages\calibre\gui2\preferences\plugboard.py", line 54, in initialize
  File "calibre_plugins.kobotouch_extended.device.driver", line 113, in settings
  File "calibre_plugins.kobotouch_extended.common", line 95, in print_formatted_log
  File "calibre_plugins.kobotouch_extended.common", line 84, in _tag_args
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 32: invalid start byte

**Comment by jgoguen** [comment] 2020-05-17 01:34
Duplicate of #87, follow along there for updates

**Closed by jgoguen** 2020-05-17 01:34 UTC
Labels: bug, duplicate
