### ISSUE TITLE
cannot import name KOBOTOUCHEXTENDED

### ISSUE THREAD

**Issue by prg011** [jgoguen/calibre-kobo-driver#111] opened 2020-07-08 21:26 UTC
```
calibre, version 4.20.0
ERROR: Unhandled exception: <b>ImportError</b>:cannot import name KOBOTOUCHEXTENDED

calibre 4.20 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 319, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 201, in load
  File "site-packages\polyglot\builtins.py", line 186, in reload
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.kobotouch_extended.__init__", line 9, in <module>
ImportError: cannot import name KOBOTOUCHEXTENDED

```

I believe (really not sure) the plugin was previously installed before installing Calibre 4.20. 
Anyway after installation of Calibre 4.20, there is no trace of the plugin. Neither in the Preferences > Plugins window nor in the AppData>Roaming>calibre>plugins folder. When I try to install it, I get the above error message.
 
I do have a _device_drivers_KOBOTOUCHEXTENDED.py.json_ file under AppData>Roaming>calibre. Tried renaming it but the end result is the same: same error message.

**Comment by jgoguen** [comment] 2020-08-01 22:13
I can't reproduce this at all. Have you tried verifying the plugin file is gone? Open Preferences, choose Miscellaneous, then click the "Open calibre configuration directory" button. Once Explorer opens, close calibre. In the "plugins" folder, if there's a file called "KoboTouchExtended.zip" delete it. Then start calibre, restart in debug mode, and try installing the plugin again. If it fails again, post the full debug log.

**Comment by jgoguen** [comment] 2020-08-08 03:46
I'm closing this for now, if you're able to update calibre to the latest available version and reproduce this, please re-open this with all the necessary details (see https://raw.githubusercontent.com/jgoguen/calibre-kobo-driver/main/.github/ISSUE_TEMPLATE/bug_report.md for the raw Markdown template, you need everything from `# Bug Report` onward) or open a new issue (which will pre-fill the template for you).

**Closed by jgoguen** 2020-08-08 03:46 UTC
Labels: needs-information
